apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "canaryjavaapp.fullname" . }}
  labels:
    {{- include "canaryjavaapp.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.host }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tlsSecret }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "canaryjavaapp.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
