apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "canaryjavaapp.fullname" . }}
  labels:
    {{- include "canaryjavaapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "canaryjavaapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if .Values.logging.enabled }}
      annotations:
        checksum/logback: {{ include (print $.Template.BasePath "/logging-configmap.yaml") . | sha256sum }}
      {{- end }}
      labels:
        {{- include "canaryjavaapp.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          {{- if .Values.logging.enabled }}
          env:
            - name: LOGGING_CONFIG
              value: /config/logback.xml
          {{- end }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.logging.enabled }}
          volumeMounts:
            - name: logback-config
              mountPath: /config
              readOnly: true
            - name: app-logs
              mountPath: {{ .Values.logging.path }}
          {{- end }}
      {{- if .Values.logging.enabled }}
      volumes:
        - name: logback-config
          configMap:
            name: {{ include "canaryjavaapp.fullname" . }}-logback
        - name: app-logs
          emptyDir:
            {{- if .Values.logging.tmpfs.enabled }}
            medium: Memory
            sizeLimit: {{ .Values.logging.tmpfs.sizeLimit }}
            {{- end }}
      {{- end }}
  strategy:
    canary:
      stableService: {{ include "canaryjavaapp.fullname" . }}
      canaryService: {{ include "canaryjavaapp.fullname" . }}-canary
      trafficRouting:
        nginx:
          stableIngress: {{ include "canaryjavaapp.fullname" . }}
      steps:
        {{- toYaml .Values.canary.steps | nindent 8 }}
