apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "canaryjavaapp.fullname" . }}
  labels:
    {{- include "canaryjavaapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "canaryjavaapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "canaryjavaapp.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
  strategy:
    canary:
      stableService: {{ include "canaryjavaapp.fullname" . }}
      canaryService: {{ include "canaryjavaapp.fullname" . }}-canary
      trafficRouting:
        nginx:
          stableIngress: {{ include "canaryjavaapp.fullname" . }}
      steps:
        {{- toYaml .Values.canary.steps | nindent 8 }}
