apiVersion: v1
kind: Service
metadata:
  name: {{ include "canaryjavaapp.fullname" . }}
  labels:
    {{- include "canaryjavaapp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "canaryjavaapp.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "canaryjavaapp.fullname" . }}-canary
  labels:
    {{- include "canaryjavaapp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "canaryjavaapp.selectorLabels" . | nindent 4 }}
